print("hello world")
print("hello world 2")
print("hello world 3")
print("hello world 4")
print("hello world 5")
print("hello world 6")
print("hello world 7")
print("hello world 8")
print("hello world 9")
print("hello world 10")
print("hello world 11")
print("hello world 12")
print("hello world 13")
print("hello world 14")
print("hello world 15")
print("hello world 16")
print("hello world 17")
print("hello world 18")